#!/bin/sh

# This script requires 'sox' and 'python'
# It also requires to have the 'parsedatetime' python library installed

alert_sound="~/Scripts/alert-sound"
message="$*"

parsed_date=$(python << END
from datetime import datetime
import parsedatetime
import sys
  
cal = parsedatetime.Calendar()
time_struct, parse_status = cal.parse("$message")
  
if parse_status:
    print(datetime(*time_struct[:6]).strftime("%Y%m%d%H%M.%S"))
else:
    sys.stderr.write("Cannot parse date\n")
    sys.exit(1)
END
) || exit 1

echo "notify-send -t 0 'Reminder' \"$message\" && play '$alert_sound'" \
  | at -t "$parsed_date"

